import protogen

enumPackage = protogen.PyImportPath("enum")


def generate(gen: protogen.Plugin):
    for f in gen.files:
        if f.generate:
            g = gen.new_generated_file("")
            g.P("# Autogenerated code. DO NOT EDIT.")
            g.P(f'"""This is an module docstring."""')

            for service in f.services:
                g.P(f"class {service.name}Client:")
                g.P(f"  def __init__(self, host: str):")
                g.P(f"    self.host = host")
                g.P()
                for method in service.methods:
                    # fmt: off
                    g.P(f"  def {method.python_name}(req: ", method.input.ident, ") -> ", method.output.ident, ":")
                    g.P(f"    pass")
                    g.P()
                    # fmt: on

            for enum in f.enums:
                g.P(f"class {enum.name}(", enum.ident("Enum"), "):")
                for value in enum.values:
                    g.P(f"  {value.name}={value.value}")

            for message in f.messages:
                g.P(f"class {message.name}:")
                g.P(f"  def __init__(self, host: str):")
                g.P(f"    self.host = host")


opts = protogen.Options()
opts.run(generate)
